"use strict";
exports.__esModule = true;
var Address_1 = require("./Address");
var Customer_1 = require("./Customer");
var Hotel_1 = require("./Hotel");
var Room_1 = require("./Room");
var customer1 = new Customer_1.Customer('sauth', 'phouek');
var address1 = new Address_1.Address('Phnom Penh', 'st 2004', 'Cambodia');
customer1.setCustomerAddress(address1);
var Room1 = new Room_1.Room(1, 2);
var Room2 = new Room_1.Room(2, 6);
var Room3 = new Room_1.Room(3, 3);
Room1.registerCustomer(customer1);
Room1.registerCustomer(customer1);
console.log(Room1);
var hotel1 = new Hotel_1.Hotel('PNC Apartment');
hotel1.setAddressHotel(address1);
hotel1.addRoomToHotel(Room1, Room2, Room3);
// console.log(hotel1);
